version: '3'

services:
  cloudflared:
    env_file: .env
    build: 
      context: ./cloudflared
      args:
      - ARCHITECTURE=${ARCHITECTURE}
      - PORT=${PORT}
    container_name: cloudflared
    restart: always
    networks:
      cloudflared_net:
        # Define a static ip for the container. The containter can be accessible by outside with this IP.
        ipv4_address: 172.28.1.1

  pihole:
    container_name: pihole
    env_file: .env
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: ${Timezone}
      # http://pi.hole/admin password.
      WEBPASSWORD: ${password}
      #Primary upstream DNS provider. it must be the static IP of Cloudflared container
      DNS1: '172.28.1.1#5053'
      # Secondary upstream DNS provider, default is Cloudflare DNS (1.1.1.1)
      DNS2: ${DNS2}
      DNSMASQ_LISTENING: nic
    # Volumes store your data between container upgrades
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: always
    depends_on:
      - cloudflared

networks:
  cloudflared_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16